# Generated by Django 5.1.6 on 2025-03-18 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Course_table', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course_table_Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=100)),
                ('coursetitle', models.TextField(max_length=100)),
                ('instructor', models.URLField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
